name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.pip
    - name: Coverage test
      run: |
        pip install coverage
        coverage run runtests.py
        coverage xml
    - name: Upload coverage report to codecov
      env:
        CODECOV: ${{ secrets.CODECOV }}
      run: |
        pip install codecov
        codecov -t ${CODECOV}
        
